# Generated by Django 6.0.3 on 2026-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='max_loans',
            field=models.PositiveIntegerField(default=1, verbose_name='max loans allowed'),
        ),
    ]
