# Generated by Django 6.0.3 on 2026-03-24 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('full_name_ar', models.CharField(max_length=200, null=True, verbose_name='full name')),
                ('full_name_fr', models.CharField(max_length=200, null=True, verbose_name='full name')),
                ('full_name_en', models.CharField(max_length=200, null=True, verbose_name='full name')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='nationality')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('bio_ar', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('bio_fr', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='biography')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('fr', 'French'), ('en', 'English'), ('other', 'Other')], default='ar', max_length=10, verbose_name='language')),
                ('year_published', models.PositiveIntegerField(blank=True, null=True, verbose_name='year published')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='cover image')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='total copies')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='available copies')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='average rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.author', verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=10, verbose_name='condition')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'book copy',
                'verbose_name_plural': 'book copies',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.book', verbose_name='book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'unique_together': {('member', 'book')},
            },
        ),
    ]
