# Generated by Django 6.0.3 on 2026-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if book is not for sale', max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='book',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp number'),
        ),
    ]
