# Generated by Django 6.0.3 on 2026-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_price_book_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='copy_type',
            field=models.CharField(choices=[('loan', 'For loan'), ('sale', 'For sale'), ('both', 'For loan and sale')], default='loan', max_length=10, verbose_name='copy type'),
        ),
    ]
