# Generated by Django 6.0.3 on 2026-04-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_book_price_book_whatsapp_number'),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('loan', 'Loan request'), ('purchase', 'Purchase request')], max_length=10, verbose_name='request type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='catalog.book', verbose_name='book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'book request',
                'verbose_name_plural': 'book requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
