# Generated by Django 6.0.3 on 2026-05-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membershipplan_max_loans'),
        ('circulation', '0002_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower_type',
            field=models.CharField(choices=[('member', 'Member'), ('visitor', 'Visitor')], default='member', max_length=10, verbose_name='borrower type'),
        ),
        migrations.AddField(
            model_name='loan',
            name='visitor_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=8, null=True, verbose_name='visitor fee'),
        ),
        migrations.AddField(
            model_name='loan',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='visitor name'),
        ),
        migrations.AddField(
            model_name='loan',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='visitor phone'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.member', verbose_name='member'),
        ),
    ]
