# Generated by Django 6.0.3 on 2026-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_loan_borrower_type_loan_visitor_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='visitor_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/ids/', verbose_name='visitor ID image'),
        ),
    ]
