# Generated by Django 6.0.3 on 2026-05-15 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membershipplan_max_loans'),
        ('catalog', '0003_bookcopy_copy_type'),
        ('circulation', '0004_loan_visitor_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='buyer name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='sold at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='catalog.book', verbose_name='book')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.admin', verbose_name='sold by')),
            ],
            options={
                'verbose_name': 'direct sale',
                'verbose_name_plural': 'direct sales',
                'ordering': ['-sold_at'],
            },
        ),
    ]
