# Generated by Django 6.0.3 on 2026-03-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_reservation', 'New reservation'), ('overdue_loan', 'Overdue loan'), ('new_review', 'New review pending approval'), ('new_member', 'New member registered'), ('loan_due_soon', 'Loan due soon'), ('loan_overdue', 'Loan overdue'), ('membership_expiring', 'Membership expiring soon'), ('reservation_ready', 'Reservation ready for pickup'), ('fine_added', 'Fine added')], max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('target_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='target model')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='target ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
